# Introduction


k-means clustering algorithm represents each cluster by its corresponding cluster centroid.the algorithm  will partition the input data into k-disjoint clusters by usinf the following steps:


1.   Form k clusters by assigning each instance to its nearest centroid
2.   Recompute the centroid of each cluster



In [ ]:
import pandas as pd

In [ ]:
ratings=[['john',5,5,2,1],['mary',4,5,3,2],['bob',4,4,4,3],['lisa',2,2,4,5],['lee',1,2,3,4],['harry',2,1,5,5]]

In [ ]:
ratings

[['john', 5, 5, 2, 1],
 ['mary', 4, 5, 3, 2],
 ['bob', 4, 4, 4, 3],
 ['lisa', 2, 2, 4, 5],
 ['lee', 1, 2, 3, 4],
 ['harry', 2, 1, 5, 5]]

In [ ]:
type(ratings)


list

In [ ]:
titles=['user','jaws','star wars','exorcist','omen']

In [ ]:
titles

['user', 'jaws', 'star wars', 'exorcist', 'omen']

In [ ]:
movies=pd.DataFrame(ratings,columns=titles)

In [ ]:
movies

user  jaws  star wars  exorcist  omen
0   john     5          5         2     1
1   mary     4          5         3     2
2    bob     4          4         4     3
3   lisa     2          2         4     5
4    lee     1          2         3     4
5  harry     2          1         5     5

# Data discussion

From the dataset, the first 3 users like action movies, and the last 3 like horror movies. Our goal is to apply k- means clustering on the users to identify groups of users with simlar movie preferences. k= 2 from the dataset

In [ ]:
from sklearn import cluster

In [ ]:
myData=movies.drop('user', axis=1)

In [ ]:
myData

jaws  star wars  exorcist  omen
0     5          5         2     1
1     4          5         3     2
2     4          4         4     3
3     2          2         4     5
4     1          2         3     4
5     2          1         5     5

In [ ]:
k_means =cluster.KMeans(n_clusters=2, max_iter=50,random_state=1)

In [ ]:
k_means

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=50,
       n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=1, tol=0.0001, verbose=0)

In [ ]:
k_means.fit(myData)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=50,
       n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=1, tol=0.0001, verbose=0)

In [ ]:
labels=k_means.labels_

In [ ]:
labels

array([0, 0, 0, 1, 1, 1], dtype=int32)

In [ ]:
pd.DataFrame(labels,index=movies.user,columns=['Cluster ID'])

Cluster ID
user             
john            0
mary            0
bob             0
lisa            1
lee             1
harry           1

K-means clustering has assigned the first 3 users to one cluster and the last 3 to the 2nd cluster.. this results are consistent with our expectations. we can also display the centroid for each of the 2 clusters

In [ ]:
centroids =k_means.cluster_centers_

In [ ]:
centroids

array([[4.33333333, 4.66666667, 3.        , 2.        ],
       [1.66666667, 1.66666667, 4.        , 4.66666667]])

In [ ]:
pd.DataFrame(centroids, columns=myData.columns)

jaws  star wars  exorcist      omen
0  4.333333   4.666667       3.0  2.000000
1  1.666667   1.666667       4.0  4.666667

the cluster can be used to determine other users clusters assignments

In [ ]:
import numpy as np

In [ ]:
testData=np.array([[4,5,1,2],[3,2,4,4],[2,3,4,1],[3,2,3,3],[5,4,1,4]])

In [ ]:
testData

array([[4, 5, 1, 2],
       [3, 2, 4, 4],
       [2, 3, 4, 1],
       [3, 2, 3, 3],
       [5, 4, 1, 4]])

In [ ]:
labels=k_means.predict(testData)

In [ ]:
labels

array([0, 1, 0, 1, 0], dtype=int32)

In [ ]:
usernames=np.array(['paul','kim','liz','tom','bill']).reshape(-1,1)

In [ ]:
usernames

array([['paul'],
       ['kim'],
       ['liz'],
       ['tom'],
       ['bill']], dtype='<U4')

In [ ]:
cols=movies.columns.tolist()

In [ ]:
cols

['user',
 'jaws',
 'star wars',
 'exorcist',
 'omen',
 'Cluster ID',
 'ClusterID',
 'Cluster ID']

In [ ]:
cols.remove('Cluster ID')

In [ ]:
cols

['user', 'jaws', 'star wars', 'exorcist', 'omen', 'ClusterID', 'Cluster ID']

In [ ]:
cols.remove('ClusterID')

In [ ]:
cols

['user', 'jaws', 'star wars', 'exorcist', 'omen', 'Cluster ID']

In [ ]:
newusers=pd.DataFrame(np.concatenate((usernames,testData,labels), axis=1),columns=cols)

In [ ]:
cols

['user', 'jaws', 'star wars', 'exorcist', 'omen', 'Cluster ID']

In [ ]:
newusers

#Hierarchial Clustering

In [ ]:
import pandas as pd


In [ ]:
myData = pd.read_csv(r"C:\\Users\\admin\\Downloads\\vertebrate.csv")

In [ ]:
thisData